// Generated by GPT4.

import nodemailer from "nodemailer";

export async function POST(req) {
  const { email, subject, text, attachments } = await req.json();

  // Create a transporter object using SMTP2GO
  const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: process.env.SMTP_PORT,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  // Define email options
  const mailOptions = {
    from: "jbarbour95@hotmail.com", // Your verified email
    to: email,
    subject: subject,
    text: text,
    attachments: attachments.map((attachment) => ({
      filename: attachment.filename,
      path: attachment.content,
      contentType: "application/pdf",
    })),
  };

  try {
    // Send email
    await transporter.sendMail(mailOptions);
    return new Response(JSON.stringify({ success: true }), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  } catch (error) {
    console.error(error);
    return new Response(JSON.stringify({ error: "Failed to send email" }), {
      status: 500,
      headers: { "Content-Type": "application/json" },
    });
  }
}
